//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_master
    {
        public long c_id { get; set; }
        public string cname { get; set; }
        public string email { get; set; }
        public string mob { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string maplocation { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string LocLat { get; set; }
        public string LocLong { get; set; }
    }
}
