//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart_master> cart_master { get; set; }
        public virtual DbSet<cart_master_details> cart_master_details { get; set; }
        public virtual DbSet<login_master> login_master { get; set; }
        public virtual DbSet<offer_master_details> offer_master_details { get; set; }
        public virtual DbSet<offerScheme> offerSchemes { get; set; }
        public virtual DbSet<order_history> order_history { get; set; }
        public virtual DbSet<order_history_details> order_history_details { get; set; }
        public virtual DbSet<order_maseter_feedback> order_maseter_feedback { get; set; }
        public virtual DbSet<order_master> order_master { get; set; }
        public virtual DbSet<order_master_details> order_master_details { get; set; }
        public virtual DbSet<order_master_payment> order_master_payment { get; set; }
        public virtual DbSet<product_master> product_master { get; set; }
        public virtual DbSet<product_review> product_review { get; set; }
        public virtual DbSet<ProductPrice> ProductPrices { get; set; }
        public virtual DbSet<pwd_Recovery> pwd_Recovery { get; set; }
        public virtual DbSet<role_master> role_master { get; set; }
        public virtual DbSet<role_master_details> role_master_details { get; set; }
        public virtual DbSet<shipping_address_master> shipping_address_master { get; set; }
        public virtual DbSet<state_price> state_price { get; set; }
        public virtual DbSet<user_master> user_master { get; set; }
    }
}
