//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_master
    {
        public long login_id { get; set; }
        public string password { get; set; }
        public string username { get; set; }
        public Nullable<long> role { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual user_master user_master { get; set; }
    }
}
