//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer_master_details
    {
        public long offer_detail_id { get; set; }
        public Nullable<long> offerId { get; set; }
        public Nullable<long> pId { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> offerrate { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
    }
}
