//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_master()
        {
            this.order_history = new HashSet<order_history>();
        }
    
        public long order_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<System.DateTime> order_datetime { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<decimal> gtotal { get; set; }
        public Nullable<long> offer_id { get; set; }
        public Nullable<long> cartIdTemp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_history> order_history { get; set; }
    }
}
