//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_master()
        {
            this.offerSchemes = new HashSet<offerScheme>();
            this.product_review = new HashSet<product_review>();
            this.ProductPrices = new HashSet<ProductPrice>();
        }
    
        public long p_id { get; set; }
        public string pname { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string unit { get; set; }
        public string nutritionImg { get; set; }
        public Nullable<decimal> shippingCharge { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<System.DateTime> uDate { get; set; }
        public Nullable<decimal> taxPer { get; set; }
        public Nullable<int> offerDisc { get; set; }
        public string offerImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offerScheme> offerSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_review> product_review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
    }
}
