//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_review
    {
        public long product_review_id { get; set; }
        public Nullable<long> pId { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<int> delete_stuats { get; set; }
    
        public virtual product_master product_master { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
