//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwd_Recovery
    {
        public int Id { get; set; }
        public string email_add { get; set; }
        public string conf_code { get; set; }
        public Nullable<int> status { get; set; }
        public string cDate { get; set; }
    }
}
