//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_master_details
    {
        public long role_detail_id { get; set; }
        public Nullable<long> roleId { get; set; }
        public string page_name { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<long> user_id { get; set; }
    
        public virtual role_master role_master { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
