//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_address_master
    {
        public long shipping_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string companyName { get; set; }
        public string line1 { get; set; }
        public string line2 { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string landmark { get; set; }
        public Nullable<decimal> mobile { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual user_master user_master { get; set; }
    }
}
